# Generated by Django 4.2 on 2023-04-23 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sm_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
