# Generated by Django 4.2 on 2023-04-23 09:50

from django.db import migrations, models
import sm_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("sm_app", "0003_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=sm_app.models.create_custom_path
            ),
        ),
    ]
