# Generated by Django 4.2 on 2023-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_userfollowing_user_who_follow_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                fields=("user_who_follow", "user_who_influence"), name="unique_pair"
            ),
        ),
    ]
