# Generated by Django 4.2 on 2023-04-23 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_userfollowing_unique_pair"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollowing",
            name="user_who_follow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="followed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfollowing",
            name="user_who_influence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="influenced_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
